### PR TITLE
Use Yaml for config file and put defaults in Config

### PR DESCRIPTION
**Pull request by whikloj**
Resolves: https://jira.duraspace.org/browse/FCREPO-2340

Also moves the definition of defaults inside the Config object.

### CODE REVIEW

**Comment by jwestgard** [comment]
I'm seeing an empty yaml file being created when I run the exporter. Has anyone else seen this?

**Comment by whikloj** [comment]
Looking into it.

**Comment by whikloj** [comment]
@ruebot @jwestgard My mistake. This should be better.

**Comment by jwestgard** [comment]
Confirmed -- getting a good yaml file now.

**Comment by jwestgard** [comment]
No, I'm not a member of this one.

**Pull request merged**
