### PR TITLE
Parse serialized RDF and export members linked to with ldp:contains

### PR DESCRIPTION
**Pull request by escowles**
Fixes https://jira.duraspace.org/browse/FCREPO-2142

### CODE REVIEW

**Comment by escowles** [comment]
@ruebot: yep, I'll do that this afternoon!

**Comment by awoods** [comment]
@escowles: where is the driver for this? I am not seeing which jar to use to run it.

**Comment by escowles** [comment]
@awoods This PR doesn't change the driver — but after #8 is merged, this doesn't run for me.  I'll try to fix that this afternoon.

**Comment by escowles** [comment]
🆗  — working on it

**Comment by awoods** [comment]
I have rebased this locally and given the following outstanding issue, works as expected.
https://jira.duraspace.org/browse/FCREPO-2154

**Comment by escowles** [comment]
@awoods I had to make a couple of small changes: adding the `<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>` to `fcrepo-import-export-driver/pom.xml` and updating one of the tests to use `parseConfiguration` instead of `parse`.  But now I've done that and pushed my updates.

**Comment by awoods** [comment]
hmm, @ruebot. I get binaries.

**Comment by escowles** [comment]
@ruebot I'm running this command and getting descriptions and binaries:

```
java -jar fcrepo-import-export-driver/target/fcrepo-import-export-driver-0.0.1-SNAPSHOT.jar --mode export --resource http://localhost:8080/rest --descDir /tmp/rdf --binDir /tmp/bin
```

**Pull request merged**
