### PR TITLE
Skipping Pairtree resources

### PR DESCRIPTION
**Pull request by escowles**
Fixes https://jira.duraspace.org/browse/FCREPO-2240

### CODE REVIEW

**Comment by escowles** [comment]
@ruebot: I've roundtripped a few resources locally and I'm not seeing the top-level PairTree resources created like your screen shot shows.  I'll load up the plantpatents dataset and see if that triggers this.

**Comment by escowles** [comment]
@ruebot: OK, I tried with the plantpatents dataset and I'm seeing the same thing as your screenshot now.  I'm also seeing a lot of errors like this:

```
WARN 17:00:10.316 (Importer) Error discovering membership resource: org.apache.jena.atlas.RuntimeIOException: java.nio.charset.MalformedInputException: Input length = 1
WARN 17:00:10.320 (riot) [line: 31, col: 10] Lexical form '10/23/2014 16:59:12' not valid for datatype http://www.w3.org/2001/XMLSchema#dateTime
WARN 17:00:10.327 (Importer) Error discovering membership resource: org.apache.jena.atlas.RuntimeIOException: java.nio.charset.MalformedInputException: Input length = 1
WARN 17:00:10.333 (riot) [line: 31, col: 10] Lexical form '10/23/2014 17:55:24' not valid for datatype http://www.w3.org/2001/XMLSchema#dateTime
```

I'm not sure if it's related or not, but now I can reproduce the issue and try to address it.

**Comment by awead** [comment]
@escowles I ran the import export process that @ruebot did with the hydra data set and I can confirm it looks off.
pairtree
For resources like `http://localhost:8986/rest/dev/63/06/0f/b9/63060fb9-757d-4f41-bb3a-78d4bc9d2171`, the pair trees are there, but for the ones like `http://localhost:8986/rest/dev/xd` is it not a pair tree, and I'm not sure why that node is there. It could be a failed import and there is more children to it that just didn't get added.

**Comment by escowles** [comment]
@ruebot @awead I've added another commit that avoids creating the PairTrees when they are parents of referenced nodes — can you re-test?

**Comment by awead** [comment]
@escowles weird. The hydra dataset now looks good. Don't know why @ruebot is having problems.

**Comment by escowles** [comment]
@ruebot I think it's worth tracking down what that warning is about — maybe in a separate ticket, though?

**Pull request merged**
