### PR TITLE
Fix potential NPE in Exporter

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://jira.duraspace.org/browse/FCREPO-2182

### CODE REVIEW

**Comment by awoods** [comment]
Rebased and ready for review.

**Comment by acoburn** [comment]
Why the null check? Doesn't the method always return a List?

**Comment by acoburn** [comment]
That is it always returns a non-null List

**Comment by awoods** [comment]
Thanks, @acoburn. I should have validated the [comment](https://github.com/fcrepo4-labs/fcrepo-import-export/pull/17#discussion_r77715349) that motivated this work.
I will close this PR.

**Comment by ajs6f** [comment]
The comment was accurate. But then someone merged [my PR](https://github.com/fcrepo4-exts/fcrepo-java-client/commit/05028c1a633296e780b9ba1ececb3c911453d6f7) for the Java client.

**Pull request closed without merging**
