### PR TITLE
Updated importer to add contained resources before storing container …

### PR DESCRIPTION
**Pull request by mikedurbin**
…RDF.

https://jira.duraspace.org/browse/FCREPO-2518

### CODE REVIEW

**Comment by mikedurbin** [comment]
Thanks for testing.  I think I fixed the error associated with binary children.

**Comment by dbernstein** [comment]
Cool I will try it again.

**Comment by mikedurbin** [comment]
This is easy enough to fix, but it looks like we went to some lengths to intentionally prevent importing the root container's triples.  

https://github.com/fcrepo4-labs/fcrepo-import-export/blob/master/src/main/java/org/fcrepo/importexport/importer/Importer.java#L360-L362

By removing that test and fixing up some other bits of code to accommodate it, the tests pass and I imagine the behavior is fixed for you.  I don't see any real problem with it, but I worry we might have had a good reason to intentionally prohibit importing the repository root, even if we didn't find a way to capture that reasoning in our integration tests.  The git blame doesn't help, as it implicates me for introducing that behavior and I don't remember why.  @escowles, do you recall any reasons why we wouldn't want to import the repository root?

**Comment by escowles** [comment]
@mikedurbin I took a look at git-blame to see when we inserted that logic to stop importing the root node, and it looks like you are the one who did it:

https://github.com/fcrepo4-labs/fcrepo-import-export/blame/master/src/main/java/org/fcrepo/importexport/importer/Importer.java#L360

Looking at those tickets, I don't see anything about the root node specifically, just general import failures.  So if you don't remember anything about why we did that, I'm fine with removing it.

**Pull request merged**
