### PR TITLE
Fix importing binary content

### PR DESCRIPTION
**Pull request by escowles**
Fixes https://jira.duraspace.org/browse/FCREPO-2188

### CODE REVIEW

**Comment by escowles** [comment]
Rebasing to fix merge conflict after #27 was merged.

**Comment by awoods** [comment]
Is this ready for review? https://jira.duraspace.org/browse/FCREPO-2188

**Comment by awoods** [comment]
Let me try this on my end...

**Comment by awoods** [comment]
I see the same WARNing, as well as:
```
WARN 14:46:52.806 (Importer) Error while importing /tmp/awoods/test/x/rdf/rest/bb/34/ab/0d/bb34ab0d-e036-4b7b-9316-ace9378dba06/internal/fcr%3Ametadata.ttl (400): Only referenceable nodes may be the value of reference properties
```
I think these are different issues from what this PR is intended to resolve... it is just that this PR enabled us to get to this next level.
I would suggest we merge this PR and create new tickets for these two new issues.

**Comment by escowles** [comment]
@ruebot It's already 1 commit, so go ahead and merge it!

**Pull request merged**
