### PR TITLE
Adding import integration test

### PR DESCRIPTION
**Pull request by escowles**
Fixes https://jira.duraspace.org/browse/FCREPO-2203

### CODE REVIEW

**Comment by mikedurbin** [comment]
@escowles is this test meant to pass now, or only after we fix those bugs?

**Comment by escowles** [comment]
@mikedurbin I think it will require fixing the ordering bug, I think it may be also showing the same errors that @bseeger mentioned with importing using auth.

**Comment by escowles** [comment]
See https://travis-ci.org/fcrepo4-labs/fcrepo-import-export/builds/158834445#L4387

**Comment by awoods** [comment]
Is there a related ticket to track this, however?

**Comment by escowles** [comment]
@awoods I created FCREPO-2203 to track this.

**Pull request closed without merging**
